# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7z030fbg484-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/a/0class/matches/DATA_CONVERT/0.21/sim/viv/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/a/0class/matches/DATA_CONVERT/0.21/sim/viv/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/a/0class/matches/DATA_CONVERT/0.21/sim/viv/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/a/0class/matches/DATA_CONVERT/0.21/sim/ise/t201706301133/READ.v
  /home/a/0class/matches/DATA_CONVERT/0.21/OUT.v
  /home/a/0class/matches/DATA_CONVERT/0.21/sim/ise/t201706301133/CTRL.v
  /home/a/0class/matches/DATA_CONVERT/0.21/DATA_CONVERT.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top DATA_CONVERT -part xa7z030fbg484-1I


write_checkpoint -force -noxdef DATA_CONVERT.dcp

catch { report_utilization -file DATA_CONVERT_utilization_synth.rpt -pb DATA_CONVERT_utilization_synth.pb }
